name: Resumen Diario Automático

on:
  schedule:
    - cron: "0 9 * * *"  # Ejecuta diario a las 9 AM UTC
  workflow_dispatch:       # Permite ejecución manual

jobs:
  generar-resumen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar el pipeline
        env:
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_DESTINATARIO: ${{ secrets.MAIL_DESTINATARIO }}
        run: python main.py --output pdf --send
